# Generated by Django 5.1.2 on 2024-10-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
