# Generated by Django 5.1.2 on 2024-10-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_like_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='total',
        ),
    ]
